apiVersion: v1
kind: Service
metadata:
  name: nginx-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
  selector:
    project: devops-with-kubernetes
    app: nginx
