kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-gp2
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: Immediate
parameters:
  type: gp2
  fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: ebs-gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
